Repository doranakan/appdeptus, pull requests merged in 2024-11, with the labels that each got.

#46 feat: sign in screen 🔐
  app.json
  app/_layout.tsx
  app/armies/_layout.tsx
  app/armies/index.tsx
  assets/resources/misc/sign_in.jpg
  assets/svg/index.ts
  assets/svg/logo.svg
  components/Background/Background.stories.tsx
  components/Background/Background.tsx
  components/Background/index.ts
  components/ScreenContainer/ScreenContainer.tsx
  components/ScreenContainer/index.ts
  components/index.ts
  modules/armies/screens/Library/Library.tsx
  modules/armies/screens/Library/index.ts
  modules/armies/screens/index.ts
  modules/root/screens/Root/Form.tsx
  modules/root/screens/Root/Root.tsx
Labels: enhancement

#47 feat: army library 📚
  app/(home)/_layout.tsx
  app/(home)/army-library.tsx
  app/(home)/games.tsx
  app/_layout.tsx
  app/armies/_layout.tsx
  app/army-builder/_layout.tsx
  app/army-builder/index.tsx
  assets/lotties/danger.json
  assets/lotties/dedicated-server.json
  assets/lotties/dice.json
  assets/lotties/plan.json
  assets/lotties/toxic-free.json
  components/Avatar/Avatar.tsx
  components/Card/Card.tsx
  components/FilterTopBar/FilterTopBar.stories.tsx
  components/FilterTopBar/FilterTopBar.tsx
  components/FilterTopBar/index.ts
  components/NavigationHeader/NavigationHeader.tsx
  components/ScreenContainer/ScreenContainer.tsx
  components/index.ts
  modules/armies/screens/CodexSelection/CodexSelection.tsx
  modules/armies/screens/CodexSelection/index.ts
  modules/armies/screens/Library/ArmyList.tsx
  modules/armies/screens/Library/Empty.tsx
  modules/armies/screens/Library/Error.tsx
  modules/armies/screens/Library/Header.tsx
  modules/armies/screens/Library/Library.tsx
  modules/armies/screens/Library/Loading.tsx
  modules/armies/screens/index.ts
  modules/games/screens/Games/Games.tsx
  modules/games/screens/Games/index.ts
  modules/games/screens/index.ts
  modules/root/screens/Root/Root.tsx
  modules/user/api/endpoints/getUserProfile.ts
  package-lock.json
  package.json
Labels: enhancement, component

#48 feat: codex selection 📖
  app/army-builder/_layout.tsx
  app/army-builder/detachment-selection.tsx
  components/Error/Error.stories.tsx
  components/Error/Error.tsx
  components/Error/index.ts
  components/FilterTopBar/FilterTopBar.tsx
  components/Loading/Loading.stories.tsx
  components/Loading/Loading.tsx
  components/Loading/index.ts
  components/ScreenContainer/ScreenContainer.tsx
  components/TabMenu/TabMenu.tsx
  components/index.ts
  constants/factions.ts
  constants/index.ts
  models/army.ts
  models/codex.ts
  modules/armies/api/endpoints/createArmy.ts
  modules/armies/api/schemas.ts
  modules/armies/screens/CodexSelection/CodexList.tsx
  modules/armies/screens/CodexSelection/CodexListItem.tsx
  modules/armies/screens/CodexSelection/CodexSelection.tsx
  modules/armies/screens/CodexSelection/Header.tsx
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/DetachmentSelection/index.ts
  modules/armies/screens/Library/ArmyList.tsx
  modules/armies/screens/index.ts
Labels: enhancement, component

#49 feat: detachment selection 🎣
  app/army-builder/_layout.tsx
  app/army-builder/composition-selection.tsx
  components/Card/Card.tsx
  components/ScreenTitle/ScreenTitle.stories.tsx
  components/ScreenTitle/ScreenTitle.tsx
  components/ScreenTitle/index.ts
  components/index.ts
  models/index.ts
  modules/armies/api/api.ts
  modules/armies/api/endpoints/index.ts
  modules/armies/api/hooks.ts
  modules/armies/api/schemas.ts
  modules/armies/components/BuilderBackground/BuilderBackground.tsx
  modules/armies/components/BuilderBackground/index.tsx
  modules/armies/components/index.ts
  modules/armies/screens/CodexSelection/CodexSelection.tsx
  modules/armies/screens/CompositionSelection/CompositionSelection.tsx
  modules/armies/screens/CompositionSelection/index.ts
  modules/armies/screens/DetachmentSelection/DetachmentList.tsx
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/DetachmentSelection/Header.tsx
  modules/armies/screens/Library/Library.tsx
  modules/armies/screens/index.ts
Labels: enhancement, component

#50 refactor: improve codex selection performances 👩🏼‍🎤
  modules/armies/screens/CodexSelection/CodexList.tsx
  modules/armies/screens/CodexSelection/CodexListItem.tsx
Labels: enhancement

#53 feat: animated codex list ✨
  components/TabMenu/TabMenuItem.tsx
  constants/animationConfigs.ts
  constants/index.ts
  modules/armies/screens/CodexSelection/CodexList.tsx
Labels: enhancement

#52 feat: unit selection screen ♟
  app/_layout.tsx
  app/army-builder/_layout.tsx
  components/BottomSheet/BottomSheet.stories.tsx
  components/BottomSheet/BottomSheet.tsx
  components/BottomSheet/index.ts
  components/BottomSheet/ref.ts
  components/Card/Card.tsx
  components/index.ts
  models/army.ts
  modules/armies/api/endpoints/createArmy.ts
  modules/armies/components/TopBar/TopBar.tsx
  modules/armies/components/TopBar/index.ts
  modules/armies/components/index.ts
  modules/armies/screens/CodexSelection/CodexList.tsx
  modules/armies/screens/CodexSelection/Header.tsx
  modules/armies/screens/DetachmentSelection/DetachmentList.tsx
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/DetachmentSelection/Header.tsx
  modules/armies/screens/EnhancementSelection/EnhacementSelection.tsx
  modules/armies/screens/EnhancementSelection/EnhancementList.tsx
  modules/armies/screens/LeaderSelection/LeaderSelection.tsx
  modules/armies/screens/LeaderSelection/index.ts
  modules/armies/screens/UnitSelection/Header.tsx
  modules/armies/screens/UnitSelection/UnitCustomizationBottomSheet.tsx
  modules/armies/screens/UnitSelection/UnitList.tsx
  modules/armies/screens/UnitSelection/UnitListItem.tsx
  modules/armies/screens/UnitSelection/UnitSelection.tsx
  modules/armies/screens/index.ts
  package-lock.json
  package.json
Labels: enhancement, component

#55 feat: warlord screen 👑
  app/army-builder/_layout.tsx
  components/BottomSheet/BottomSheet.stories.tsx
  components/Input/Input.tsx
  components/NavigationHeader/NavigationHeader.stories.tsx
  components/NavigationHeader/NavigationHeader.tsx
  components/Scoreboard/Scoreboard.stories.tsx
  components/UnitListItem/UnitListItem.stories.tsx
  models/army.ts
  models/codex.ts
  models/detachment.ts
  models/game.ts
  models/unit.ts
  modules/armies/api/endpoints/createArmy.ts
  modules/armies/api/endpoints/deleteArmy.ts
  modules/armies/api/endpoints/getUnitList.ts
  modules/armies/api/schemas.ts
  modules/armies/components/TopBar/TopBar.tsx
  modules/armies/screens/CodexSelection/CodexList.tsx
  modules/armies/screens/CodexSelection/Header.tsx
  modules/armies/screens/DetachmentSelection/DetachmentList.tsx
  modules/armies/screens/DetachmentSelection/Header.tsx
  modules/armies/screens/EnhancementSelection/EnhancementList.tsx
  modules/armies/screens/EnhancementSelection/Header.tsx
  modules/armies/screens/LeaderSelection/Header.tsx
  modules/armies/screens/LeaderSelection/LeaderSelectionList.tsx
  modules/armies/screens/Library/ArmyList.tsx
  modules/armies/screens/Library/Header.tsx
  modules/armies/screens/UnitSelection/Header.tsx
  modules/armies/screens/UnitSelection/UnitCustomizationBottomSheet.tsx
  modules/armies/screens/UnitSelection/UnitList.tsx
  modules/armies/screens/WarlordSelection/Header.tsx
  modules/armies/screens/WarlordSelection/NameInput.tsx
  modules/armies/screens/WarlordSelection/WarlordList.tsx
  modules/armies/screens/WarlordSelection/WarlordSelection.tsx
  modules/games/api/endpoints/createGame.ts
  modules/games/api/endpoints/endGame.ts
  modules/games/api/endpoints/getGameList.ts
  modules/games/api/endpoints/getNewGame.ts
  modules/games/api/endpoints/startGame.ts
  modules/games/api/realtime/gameUpdates.ts
  modules/games/api/schemas.ts
Labels: enhancement

#56 feat: army screen 🪖
  app/army/[id].tsx
  app/army/_layout.tsx
  components/Card/Card.tsx
  components/EnhancementListItem/EnhancementListItem.stories.tsx
  components/EnhancementListItem/EnhancementListItem.tsx
  components/EnhancementListItem/index.ts
  components/ScreenContainer/ScreenContainer.tsx
  components/index.ts
  modules/armies/screens/Army/Army.tsx
  modules/armies/screens/Army/CompositionTab.tsx
  modules/armies/screens/Army/EnhancementList.tsx
  modules/armies/screens/Army/UnitList.tsx
  modules/armies/screens/Army/index.ts
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/EnhancementSelection/EnhancementList.tsx
  modules/armies/screens/Library/ArmyList.tsx
  modules/armies/screens/index.ts
Labels: enhancement, component

#57 feat: delete army 🗑️
  components/BottomSheet/BottomSheet.stories.tsx
  components/BottomSheet/BottomSheet.tsx
  components/BottomSheet/index.ts
  modules/armies/screens/Army/Army.tsx
  modules/armies/screens/Army/OptionsBottomSheet.tsx
  modules/armies/screens/Army/TopContainer.tsx
  modules/armies/screens/Army/ref.ts
  modules/armies/screens/UnitSelection/UnitCustomizationBottomSheet.tsx
  modules/armies/screens/UnitSelection/UnitList.tsx
  modules/armies/screens/UnitSelection/ref.ts
Labels: enhancement

#58 feat: army editing 📝
  app/army-builder/[id].tsx
  app/army-builder/_layout.tsx
  modules/armies/api/endpoints/createArmy.ts
  modules/armies/api/endpoints/updateArmy.ts
  modules/armies/api/utils.ts
  modules/armies/screens/Army/OptionsBottomSheet.tsx
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/LeaderSelection/LeaderSelectionList.tsx
  modules/armies/screens/UnitSelection/UnitList.tsx
  modules/armies/screens/WarlordSelection/Header.tsx
  package-lock.json
  package.json
Labels: enhancement

#59 feat: game tab 🎲🎲
  app/games/_layout.tsx
  app/games/new.tsx
  components/Avatar/Avatar.tsx
  components/BottomSheet/BottomSheet.stories.tsx
  components/EmptyListItem/EmptyListItem.stories.tsx
  components/EmptyListItem/EmptyListItem.tsx
  components/EmptyListItem/index.ts
  components/PlayerTag/PlayerTag.stories.tsx
  components/PlayerTag/PlayerTag.tsx
  components/PlayerTag/index.ts
  components/index.ts
  modules/armies/screens/Library/ArmyList.tsx
  modules/games/api/endpoints/getGameList.ts
  modules/games/api/schemas.ts
  modules/games/screens/Games/GameList.tsx
  modules/games/screens/Games/GameListItem.tsx
  modules/games/screens/Games/Games.tsx
  modules/games/screens/Games/Header.tsx
  modules/games/screens/NewGame/NewGame.tsx
  modules/games/screens/NewGame/index.ts
  modules/games/screens/index.ts
  package-lock.json
  package.json
Labels: enhancement, component

#60 feat: new game screen 🎍
  app/games/new/[gameId].tsx
  app/games/new/_layout.tsx
  app/games/new/index.tsx
  assets/lotties/no-war.json
  components/BottomSheet/BottomSheet.tsx
  components/Card/Card.tsx
  components/EmptyListItem/EmptyListItem.stories.tsx
  components/EmptyListItem/EmptyListItem.tsx
  components/GameDataTable/GameDataTable.stories.tsx
  components/GameDataTable/GameDataTable.tsx
  components/GameDataTable/index.ts
  components/VersusBackground/VersusBackground.stories.tsx
  components/VersusBackground/VersusBackground.tsx
  components/VersusBackground/index.ts
  components/index.ts
  modules/armies/screens/Library/ArmyList.tsx
  modules/games/api/api.ts
  modules/games/api/endpoints/deleteGame.ts
  modules/games/api/endpoints/index.ts
  modules/games/api/hooks.ts
  modules/games/screens/Games/GameList.tsx
  modules/games/screens/Games/GameListItem.tsx
  modules/games/screens/Games/Header.tsx
  modules/games/screens/Join/Join.tsx
  modules/games/screens/Join/index.ts
  modules/games/screens/New/New.tsx
  modules/games/screens/New/QRCodeBottomSheet.tsx
  modules/games/screens/New/index.ts
  modules/games/screens/New/ref.ts
  modules/games/screens/NewGame/NewGame.tsx
  modules/games/screens/NewGame/index.ts
  modules/games/screens/index.ts
Labels: enhancement, component

#62 build: upgrade to expo 52 🚀
  app/[...not-found].tsx
  app/_layout.tsx
  components/ArmyBackground/ArmyBackground.tsx
  components/Background/Background.tsx
  components/BottomSheet/BottomSheet.tsx
  modules/root/screens/NotFound/NotFound.tsx
  modules/root/screens/NotFound/index.ts
  modules/root/screens/index.ts
  package-lock.json
  package.json
Labels: bug, enhancement

#63 feat: game screen 🎮
  components/ArmyBackground/ArmyBackground.stories.tsx
  components/ArmyListItem/ArmyListItem.stories.tsx
  components/ArmyRoster/ArmyRoster.stories.tsx
  components/ArmyRoster/ArmyRoster.tsx
  components/ArmyRoster/index.ts
  components/Background/Background.stories.tsx
  components/GameDataTable/GameDataTable.tsx
  components/Input/Input.stories.tsx
  components/TabMenu/TabMenu.tsx
  components/VersusBackground/VersusBackground.tsx
  components/index.ts
  models/game.ts
  models/userProfile.ts
  modules/armies/screens/Army/CompositionTab.tsx
  modules/armies/screens/Army/UnitList.tsx
  modules/games/api/api.ts
  modules/games/api/endpoints/getEndedGameList.ts
  modules/games/api/endpoints/getGame.ts
  modules/games/api/endpoints/getNewGame.ts
  modules/games/api/endpoints/index.ts
  modules/games/api/hooks.ts
  modules/games/api/schemas.ts
  modules/games/components/GameDetail/GameDetail.tsx
  modules/games/components/GameDetail/index.ts
  modules/games/components/GamePreview/GamePreview.tsx
  modules/games/components/GamePreview/index.ts
  modules/games/components/index.ts
  modules/games/screens/Game/ActiveView.tsx
  modules/games/screens/Game/Commands.tsx
  modules/games/screens/Game/EndedView.tsx
  modules/games/screens/Game/Game.tsx
  modules/games/screens/Game/GameDetail.tsx
  modules/games/screens/Join/Join.tsx
  modules/games/screens/New/New.tsx
  modules/games/screens/Tab/ActiveGameTopBar.tsx
  modules/games/screens/Tab/GameList.tsx
  modules/games/screens/Tab/GameListItem.tsx
  modules/games/screens/Tab/Header.tsx
  modules/games/screens/Tab/Tab.tsx
  modules/user/api/schemas.ts
Labels: enhancement, component

#64 feat: ended games 💯
  components/Scoreboard/Scoreboard.tsx
  modules/games/components/Background/Background.tsx
  modules/games/components/Background/index.ts
  modules/games/components/index.ts
  modules/games/screens/Game/ActiveView.tsx
  modules/games/screens/Game/EndedView.tsx
  modules/games/screens/Join/Join.tsx
  modules/games/screens/New/New.tsx
  modules/games/screens/Tab/GameListItem.tsx
  modules/games/screens/Tab/Tab.tsx
Labels: enhancement, component

#65 refactor: adjust data models for new database schema ⛑️
  app/army-builder/_layout.tsx
  components/ArmyRoster/ArmyRoster.stories.tsx
  components/ArmyRoster/ArmyRoster.tsx
  components/Scoreboard/Scoreboard.stories.tsx
  components/UnitListItem/UnitListItem.stories.tsx
  components/UnitListItem/UnitListItem.tsx
  models/army.ts
  models/unit.ts
  modules/armies/api/endpoints/createArmy.ts
  modules/armies/api/endpoints/getUnitList.ts
  modules/armies/api/endpoints/updateArmy.ts
  modules/armies/api/schemas.ts
  modules/armies/api/utils.ts
  modules/armies/components/TopBar/TopBar.tsx
  modules/armies/hooks/index.ts
  modules/armies/hooks/useAllUnits.ts
  modules/armies/hooks/useModelCount.ts
  modules/armies/hooks/useUnitCount.ts
  modules/armies/hooks/useWarlord.ts
  modules/armies/screens/Army/Army.tsx
  modules/armies/screens/Army/CompositionTab.tsx
  modules/armies/screens/Army/TopContainer.tsx
  modules/armies/screens/DetachmentSelection/DetachmentSelection.tsx
  modules/armies/screens/LeaderSelection/LeaderSelectionList.tsx
  modules/armies/screens/Tab/ArmyList.tsx
  modules/armies/screens/UnitSelection/UnitList.tsx
  modules/armies/screens/WarlordSelection/WarlordList.tsx
  modules/games/api/endpoints/createGame.ts
  modules/games/api/endpoints/startGame.ts
  modules/games/api/schemas.ts
  modules/games/components/GamePreview/GamePreview.tsx
  modules/games/screens/Game/ActiveView.tsx
  modules/games/screens/Game/EndedView.tsx
  modules/games/screens/Game/GameDetail.tsx
  modules/games/screens/Join/Join.tsx
  modules/games/screens/New/New.tsx
Labels: enhancement

#67 feat: add embarked unit list item 🚌
  components/UnitListItem/UnitListItem.stories.tsx
  components/UnitListItem/UnitListItem.tsx
Labels: component

#68 refactor: game creation flow 🎲
  app/games/join/[gameId].tsx
  app/games/join/_layout.tsx
  app/games/new/[gameId].tsx
  app/games/new/_layout.tsx
  app/games/new/army-selection.tsx
  app/games/new/index.tsx
  modules/games/components/NewGameBottomSheet/NewGameBottomSheet.tsx
  modules/games/components/NewGameBottomSheet/index.ts
  modules/games/components/NewGameBottomSheet/ref.ts
  modules/games/components/index.ts
  modules/games/screens/ArmySelection/ArmySelection.tsx
  modules/games/screens/ArmySelection/index.ts
  modules/games/screens/New/New.tsx
  modules/games/screens/New/index.ts
  modules/games/screens/Tab/Header.tsx
  modules/games/screens/index.ts
Labels: enhancement, component

#69 feat: leader selection in game flow 🤺
  app/games/join/[gameId].tsx
  app/games/new/_layout.tsx
  app/games/new/leader-selection.tsx
  models/unit.ts
  modules/armies/screens/LeaderSelection/LeaderSelection.tsx
  modules/games/screens/LeaderSelection/LeaderSelection.tsx
  modules/games/screens/LeaderSelection/LeaderSelectionList.tsx
  modules/games/screens/LeaderSelection/index.ts
  modules/games/screens/index.ts
Labels: enhancement

#70 feat: embarked units selection 🚎
  app/army-builder/_layout.tsx
  app/games/new/_layout.tsx
  app/games/new/embarked-selection.tsx
  components/UnitListItem/UnitListItem.stories.tsx
  components/UnitListItem/UnitListItem.tsx
  hooks/index.ts
  hooks/useAllUnits.ts
  hooks/useCrew.ts
  hooks/useModelCount.ts
  hooks/useUnitCount.ts
  hooks/useWarlord.ts
  models/unit.ts
  modules/armies/screens/Army/TopContainer.tsx
  modules/armies/screens/UnitSelection/UnitSelection.tsx
  modules/games/components/GamePreview/GamePreview.tsx
  modules/games/screens/EmbarkedSelection/EmbarkedSelection.tsx
  modules/games/screens/EmbarkedSelection/EmbarkedSelectionList.tsx
  modules/games/screens/EmbarkedSelection/EmbarkedUnitBottomSheet.tsx
  modules/games/screens/EmbarkedSelection/index.ts
  modules/games/screens/EmbarkedSelection/ref.ts
  modules/games/screens/Game/GameDetail.tsx
  modules/games/screens/LeaderSelection/LeaderSelectionList.tsx
  modules/games/screens/index.ts
Labels: enhancement

#71 feat: double check screen 📋
  app/games/new/_layout.tsx
  app/games/new/double-check.tsx
  modules/games/screens/ArmySelection/ArmySelection.tsx
  modules/games/screens/DoubleCheck/DoubleCheck.tsx
  modules/games/screens/DoubleCheck/index.ts
  modules/games/screens/index.ts
Labels: enhancement

#72 refactor: game creation flow 🕹️
  app.json
  app/(home)/_layout.tsx
  app/_layout.tsx
  app/army-builder/_layout.tsx
  app/army/_layout.tsx
  app/games/_layout.tsx
  app/games/join/_layout.tsx
  app/games/new/_layout.tsx
  app/games/new/camera.tsx
  app/games/new/qr-code.tsx
  assets/lotties/qr-code.json
  components/ArmyRoster/ArmyRoster.tsx
  constants/index.ts
  constants/navigationConfigs.ts
  modules/games/components/NewGameBottomSheet/NewGameBottomSheet.tsx
  modules/games/constants/index.ts
  modules/games/constants/newGame.ts
  modules/games/screens/Camera/Camera.tsx
  modules/games/screens/Camera/index.tsx
  modules/games/screens/QRCode/QRCode.tsx
  modules/games/screens/QRCode/index.tsx
  modules/games/screens/index.ts
  package-lock.json
  package.json
Labels: enhancement, component
